### ISSUE TITLE
samples/sample1 includes odd character sequences

### ISSUE THREAD

**Issue by ptitzler** [IBM/MAX-Text-Summarizer#12]
`samples/sample1.json` contains character sequences, such as `-lrb-` and `-rrb-`, `@highlight`,  and `__...__`
Do they have any significance? If they don't, we probably shouldn't include them. If they do and they impact the result we need to explain them.

**Comment by autoih** [comment]
@ptitzler, I think the original dataset includes this character, because they are from email dataset. I'd prefer to keep this, because they are involved in the training process. In the way, a user probably can input an email blindly to see the summarized result. c.c. @xuhdev

**Comment by autoih** [comment]
I prefer to keep the content of an email. @xuhdev, any suggestions?

**Comment by xuhdev** [comment]
If the strings that appear to be nonsense are crypted from email addresses, I think it makes sense to keep them, perhaps with an explanation in README.
