### ISSUE TITLE
List important of miscellaneous fixes at Release V1.1.0

### ISSUE THREAD

**Issue by autoih** [IBM/MAX-Text-Summarizer#26]
@xuhdev, can you summarize the most important fixes, instead of `miscellaneous fixes`?

**Comment by xuhdev** [comment]
They are mostly README fixes and link fixes.

**Comment by autoih** [comment]
In this case, please add as what you mentioned, README and link fixes. Thanks.

**Comment by xuhdev** [comment]
Fixed
