### ISSUE TITLE
Is this project still supported? 

### ISSUE THREAD

**Issue by zacaintmyname** [IBM/MAX-Text-Summarizer#45]
Hi Team, 

Not reporting a bug, but wanted to know if I can speak with someone who is running this project - might have a use-case that you might find interesting! zackyeo@sg.ibm.com

**Comment by bdwyer2** [comment]
@xuhdev

**Comment by zacaintmyname** [comment]
Thank you!

**Comment by bdwyer2** [comment]
Hi @zacaintmyname, I believe this project still is supported. I left IBM earlier this year but @xuhdev is still on the team at IBM and he can probably let you know if this is still a priority.

**Comment by zacaintmyname** [comment]
Thanks you @bdwyer2! Appreciate the reply 👍

**Comment by unk1911** [comment]
great product btw! just discovered it yesterday.

(p.s. there's no way to configure the size of the summary, is there? to make it longer or shorter, etc...?)

**Comment by xuhdev** [comment]
Thanks @bdwyer2 , we have started talking offline.
